clear;
Fs=1000;
N=1000;
faxis=Fs*(0:N)/N;
t=0:1/Fs:1;
figure(1)
plot(t,sin(2*pi*10*t)+1/3*sin(2*pi*30*t))
title('函数图像')
f=sin(2*pi*10*t)+1/3*sin(2*pi*30*t);
fmax=max(f);
fmin=max(-f);
%vpp
vpp=fmax+fmin;
fzero_index=find(f<0.01);
%f
frequency=Fs/(fzero_index(2)-fzero_index(1));
ff=fft(f);
yff=ff*2/N;
yff=abs(yff(1:N/2+1));
figure(2)
plot(0:N/2,yff)
title('频谱图')
figure(3)
tol=0.01;
temp=ff(1:N/2)*2/N;
temp(abs(temp)<0.01)=0;
phase=angle(temp);
%phi
plot(faxis(1:N/2),phase)
title('相位谱')
%rms
fmean=mean(f(1:Fs/frequency));
frms=rms(f(1:Fs/frequency));
%std
fstd=std(f(1:Fs/frequency));